### PR TITLE
SecureBootConfigDxe: Implement parsing missing hashes

### LINKED ISSUE #1365: Can't delete signature of enrolled EFI file from DB as it's not shown
### Component

Dasharo firmware

### Device

Hardkernel Odroid H4

### Dasharo version

v0.9.0

### Dasharo Tools Suite version

_No response_

### Test case ID

_No response_

### Brief summary

After enrolling EFI file to DB I can't delete it without resetting keys to default as it doesn't show up in `Delete Signature` submenu.

### How reproducible

100%

### How to reproduce

1. Enroll EFI file signature
2. Go to `DB Options` -> `Delete Signature`
3. See that there is no enrolled signature to be deleted

### Expected behavior

```
/------------------------------------------------------------------------------\
|                              Delete Signature                                |
\------------------------------------------------------------------------------/

   Microsoft Windows          [ ]                        PKCS7_GUID
   Production PCA 2011
   Microsoft Corporation      [ ]
   UEFI CA 2011
   Windows UEFI CA 2023       [ ]
   Microsoft UEFI CA 2023     [ ]
   <Enrolled filename or SHA> [ ]
```

### Actual behavior

```
/------------------------------------------------------------------------------\
|                              Delete Signature                                |
\------------------------------------------------------------------------------/

   Microsoft Windows          [ ]                        PKCS7_GUID
   Production PCA 2011
   Microsoft Corporation      [ ]
   UEFI CA 2011
   Windows UEFI CA 2023       [ ]
   Microsoft UEFI CA 2023     [ ]
```

### Screenshots

_No response_

### Additional context

* The only keys available are default ones (after resetting them to default)
* The file signature is enrolled as I can boot file with Secure Boot enabled

### Solutions you've tried

`> Reset to default Secure Boot Keys`

### PR DESCRIPTION
**Pull request by miczyg1**
Some hashes were simply ignored (lack of all CompareGuid in conditions) and it caused the browser to enter an infinite loop. Because CertList variable was never updated, the exit condition for the while loop never met.

Also add formatting for displaying image hashes or certificate hashes instead of prue GUIDs.

Fixes https://github.com/Dasharo/dasharo-issues/issues/1365

TEST=Enroll DTS grubx64.efi to DB then delete its signature from DB using the Secure Boot menu on QEMU OVMF.

### CODE REVIEW

**Comment by pietrushnic** [comment]
@miczyg1 I wonder what upstream would say about that.

**Comment by miczyg1** [comment]
> @miczyg1 I wonder what upstream would say about that.

They should probably accept that, because it is clearly full of bugs...

**Comment by pietrushnic** [comment]
> > @miczyg1 I wonder what upstream would say about that.
> 
> They should probably accept that, because it is clearly full of bugs...

@miczyg1 in that case, let's try to upstream.

File: SecurityPkg/VariableAuthenticated/SecureBootConfigDxe/SecureBootConfigImpl.c [hunk 1]
```diff
@@ -2632,14 +2637,10 @@ UpdateDeletePage (
 
   while ((ItemDataSize > 0) && (ItemDataSize >= CertList->SignatureListSize)) {
     if (CompareGuid (&CertList->SignatureType, &gEfiCertRsa2048Guid) ||
```
Comment (miczyg1) [inline SecurityPkg/VariableAuthenticated/SecureBootConfigDxe/SecureBootConfigImpl.c]: This line is still wrong.

gEfiCertRsa2048Guid holds a modulus of RSA2048 key and is not a cert. SO display must be different than X509 cert or a simple SHA hash

Comment (miczyg1) [reply SecurityPkg/VariableAuthenticated/SecureBootConfigDxe/SecureBootConfigImpl.c]: Fixed it https://github.com/Dasharo/edk2/compare/79c3d3871ecab8d9084980028ec4e742a8287706..530eb27ef2bda9731211c1e3493eb9b8328c615d

**Comment by miczyg1** [comment]
@mkopec mind looking at this as well?

**Review by mkopec — APPROVED** [review]
