### PR TITLE
Nvc boot optimization

### LINKED ISSUE #454: SD card is not recognized as bootable
**Dasharo version**
v1.4.0
https://docs.dasharo.com/variants/novacustom_nv4x_tgl/releases/#v140-2023-02-24

**Affected component(s) or functionality**
Booting into kernel stored on SD card

**Brief summary**
I'm unable to boot into Linux from SD card, it seems the card is not recognized. No corresponding menu option is rendered in any place where bootable USB sticks normally show up (alongside the always-present iPXE Network Boot and UEFI Shell):
- Boot Manager Menu (F7)
- Setup (F2) -> One Time Boot
- Setup (F2) -> Boot Maintenance Manager -> Boot Next Value
- Setup (F2) -> Boot Maintenance Manager -> Boot Options -> Change Boot Order

**How reproducible**
Always.

**Steps to reproduce the behavior**
1. Plug bootable SD card into the SD card slot (example partitioning scheme given below)
2. Power on device
3. Try one of the options listed in the *Brief summary* section
4. Menu entry for the SD card is missing

**Expected behavior**
A menu option for the SD card should be shown, and if chosen, the device should boot into the kernel stored on the card.

**Actual behavior**
No menu option for the SD card is generated, thus it is not possible to boot from SD card.

**Additional context**

Partitioning scheme:
`# parted /dev/mmcblk0 -- print` (executed from `archlinux-2023.06.01-x86_64.iso`)
```text
Model: SD SH64G (sd/mmc)
Disk /dev/mmcblk0: 63.9GB
Sector size (logical/physical): 512B/512B
Partition Table: gpt
Disk Flags: 

Number  Start   End    Size    File system  Name    Flags
 1      1049kB  512MB  511MB   fat32        ESP     boot, esp
 2      512MB   528MB  16.8MB               header
```
_Dasharo firmware logs_
SD card plugged in before boot, booting into [DTS 1.2.0](https://3mdeb.com/open-source-firmware/DTS/v1.2.0/dts-base-image-v1.2.0.wic.gz) using an USB stick plugged into the USB-A port on the right side of the device.
`cbmem -1`:
[cbmem_1_with_sdcard.log](https://github.com/Dasharo/dasharo-issues/files/11655796/cbmem_1_with_sdcard.log)

No SD card plugged in, booting into [DTS 1.2.0](https://3mdeb.com/open-source-firmware/DTS/v1.2.0/dts-base-image-v1.2.0.wic.gz) using an USB stick plugged into the USB-A port on the right side of the device.
`cbmem -1`:
[cbmem_1_without_sdcard.log](https://github.com/Dasharo/dasharo-issues/files/11655804/cbmem_1_without_sdcard.log)

_Additional notes_
- Flashing exactly the same image (including the partitioning scheme) to an USB stick and booting that works fine
- The SD card is detected and can be read and written to fine after boot into `nixos-minimal-23.05.553.e7603eba51f-x86_64-linux.iso` or `archlinux-2023.06.01-x86_64.iso` from USB stick
- The SD card is not detected after boot into  [DTS 1.2.0](https://3mdeb.com/open-source-firmware/DTS/v1.2.0/dts-base-image-v1.2.0.wic.gz) via USB stick. `dmesg -w` logs nothing new when the card is unplugged and plugged in again
- I am running the official Dasharo v1.4.0 for NV40MZ TGL here, however, the IME is disabled, which is normally not the case. This is because I ran a custom modification of v1.4.0 before that I used to disable the IME (see Matrix chat), and the IME does not seem to be automatically enabled again by the official v1.4.0. I did not test if booting SD cards worked fine before I disabled the IME
- SD card is a SanDisk Max Endurance 64GB MicroSD XC card (with passive adaptor)

Happy to collect more information if necessary.

**Solutions you've tried**

An different SD card with a different partitioning scheme (MBR-based) is also not recognized (this is `archlinux-2023.06.01-x86_64.iso` flashed to the card, which works via a USB stick):
```text
Model: SD SH64G (sd/mmc)
Disk /dev/mmcblk0: 63.9GB
Sector size (logical/physical): 512B/512B
Partition Table: msdos
Disk Flags: 

Number  Start  End    Size    Type     File system  Flags
 2      813MB  828MB  15.7MB  primary  fat16        esp
```

### PR DESCRIPTION
**Pull request by miczyg1**
The PR introduced the following changes:

1. Backports an option to control SD/MMC timeout via PCD at build time (integrated in coreboot). By setting a lower timeout on SD/MMC init, it fixes the problem with long boot time on NV4x. However it does not fix https://github.com/Dasharo/dasharo-issues/issues/454
2. Reverts the change  https://github.com/Dasharo/edk2/commit/ca98d24b188813d1a919a8c75417910630c6f9d2 which broke the Continue hotkey (the enter key was passed e.g. to GRUb bootloader and one was unable to control the menu as GRUB got the key and booted its first priority)
3. Refreshes the logo at ReadyToBoot event. It results in a clear screen if Continue hotkey is used, instead of leaving half of the progress bar and strings left on the screen.

### CODE REVIEW

**Comment by miczyg1** [comment]
The PR breaks the vboot pop-up. When enter is pressed to skip the window, it also skips the menu prompt. it seems like the key was not dequeued.

**Comment by miczyg1** [comment]
> The PR breaks the vboot pop-up. When enter is pressed to skip the window, it also skips the menu prompt. it seems like the key was not dequeued.

Fixed by https://github.com/Dasharo/edk2/pull/58/commits/d435d5ec7a77a1357f20ac21df6206ecab285247

File: UefiPayloadPkg/Library/PlatformBootManagerLib/PlatformBootManager.c [hunk 1]
```diff
@@ -1063,18 +1076,29 @@ PlatformBootManagerAfterConsole (
...
   WarnIfRecoveryBoot ();
 
   BootLogoEnableLogo ();
 
+  //
+  // Register ENTER as CONTINUE key
+  //
+  Enter.ScanCode    = SCAN_NULL;
+  Enter.UnicodeChar = CHAR_CARRIAGE_RETURN;
+  EfiBootManagerRegisterContinueKeyOption (0, &Enter, NULL);
```
Comment (krystian-hebel) [inline UefiPayloadPkg/Library/PlatformBootManagerLib/PlatformBootManager.c:1097]: Does this include Enter on numpad? I always find it annoying when it doesn't work.

File: UefiPayloadPkg/Library/PlatformBootManagerLib/PlatformBootManager.c [hunk 2]
```diff
@@ -1039,6 +1032,26 @@ PrintSolStrings (
...
+**/
+VOID
+EFIAPI
+RefreshLogo (
+  IN EFI_EVENT    Event,
+  IN VOID         *Context
+  )
+{
+  gBS->CloseEvent (Event);
+  gBS->Stall (100 * 1000);
```
Comment (krystian-hebel) [inline UefiPayloadPkg/Library/PlatformBootManagerLib/PlatformBootManager.c]: Can this be moved after screen is redrawn?

Why is this delay even needed in the first place? Just to show 100% on progress bar for a while?

File: UefiPayloadPkg/Library/PlatformBootManagerLib/PlatformBootManager.c [hunk 3]
```diff
@@ -1039,6 +1032,26 @@ PrintSolStrings (
   }
 }
 
+/**
+  Refresh the logo on ReadyToBoto event. It will clear the screen from strings
```
Comment (krystian-hebel) [inline UefiPayloadPkg/Library/PlatformBootManagerLib/PlatformBootManager.c]:
```suggestion
  Refresh the logo on ReadyToBoot event. It will clear the screen from strings

```

File: UefiPayloadPkg/Library/PlatformBootManagerLib/PlatformBootManager.c [hunk 4]
```diff
@@ -709,6 +702,7 @@ PlatformBootManagerBeforeConsole (
   //
   FilterAndProcess (&gEfiPciRootBridgeIoProtocolGuid, NULL, Connect);
 
+  PlatformConsoleInit ();
```
Comment (krystian-hebel) [inline UefiPayloadPkg/Library/PlatformBootManagerLib/PlatformBootManager.c:705]: Not really related to this change, but have you tested if output still works if console is initialized before `EfiBootManagerDispatchDeferredImages()`?

File: UefiPayloadPkg/Library/PlatformBootManagerLib/PlatformBootManager.c (hunk 1 above)
Comment (miczyg1) [reply UefiPayloadPkg/Library/PlatformBootManagerLib/PlatformBootManager.c:1097]: Well, haven't checked :) But probably yes.

File: UefiPayloadPkg/Library/PlatformBootManagerLib/PlatformBootManager.c (hunk 4 above)
Comment (miczyg1) [reply UefiPayloadPkg/Library/PlatformBootManagerLib/PlatformBootManager.c:705]: PlatformConsoleInit simply adds a PCI UART, so it will work as soon as Root Bridge IO is connected

File: UefiPayloadPkg/Library/PlatformBootManagerLib/PlatformBootManager.c (hunk 2 above)
Comment (miczyg1) [reply UefiPayloadPkg/Library/PlatformBootManagerLib/PlatformBootManager.c]: >  Just to show 100% on progress bar for a while?

Sort of... We may get rid of that I think

Comment (miczyg1) [reply UefiPayloadPkg/Library/PlatformBootManagerLib/PlatformBootManager.c]:
```suggestion
```

File: UefiPayloadPkg/Library/PlatformBootManagerLib/PlatformBootManager.c (hunk 4 above)
Comment (krystian-hebel) [reply UefiPayloadPkg/Library/PlatformBootManagerLib/PlatformBootManager.c:705]: Are you sure about that? I thought it also enabled stuff that depends on GOP, which in turn may depend on OptionROM.

Comment (miczyg1) [reply UefiPayloadPkg/Library/PlatformBootManagerLib/PlatformBootManager.c:705]: Yes, I am sure: https://github.com/Dasharo/edk2/blob/dasharo/UefiPayloadPkg/Library/PlatformBootManagerLib/PlatformConsole.c#L538

It handles only PS2 keybaord and Intel PCI Serial ports

File: UefiPayloadPkg/Library/PlatformBootManagerLib/PlatformBootManager.c (hunk 1 above)
Comment (miczyg1) [reply UefiPayloadPkg/Library/PlatformBootManagerLib/PlatformBootManager.c:1097]: Yup, NUM ENTER also works (at least with USB KBD)

File: UefiPayloadPkg/Library/PlatformBootManagerLib/PlatformBootManager.c [hunk 5]
```diff
@@ -1039,6 +1032,26 @@ PrintSolStrings (
...
+**/
+VOID
+EFIAPI
+RefreshLogo (
+  IN EFI_EVENT    Event,
+  IN VOID         *Context
+  )
+{
+  gBS->CloseEvent (Event);
+  gST->ConOut->ClearScreen (gST->ConOut);
```
Comment (mkopec) [inline UefiPayloadPkg/Library/PlatformBootManagerLib/PlatformBootManager.c:1051]: This causes a short flcker before the logo is displayed again. Would be nice if we could do this without flickering

**Review by mkopec — APPROVED** [review]

File: UefiPayloadPkg/Library/PlatformBootManagerLib/PlatformBootManager.c (hunk 5 above)
Comment (miczyg1) [reply UefiPayloadPkg/Library/PlatformBootManagerLib/PlatformBootManager.c:1051]: You are asking for too much. Flickering was also present earlier if you did not press any button.

Comment (mkopec) [reply UefiPayloadPkg/Library/PlatformBootManagerLib/PlatformBootManager.c:1051]: Ok, it was more of a "Would Be Nice" thing than a request for change.
